package com.community.community.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.conversation_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private String conversationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_id
     *
     * @return the value of message.from_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_id
     *
     * @param fromId the value for message.from_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_id
     *
     * @return the value of message.to_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_id
     *
     * @param toId the value for message.to_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.conversation_id
     *
     * @return the value of message.conversation_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public String getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.conversation_id
     *
     * @param conversationId the value for message.conversation_id
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Mon Feb 20 08:17:41 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return "Message{" +
                "id=" + id +
                ", fromId=" + fromId +
                ", toId=" + toId +
                ", conversationId='" + conversationId + '\'' +
                ", status=" + status +
                ", createTime=" + createTime +
                ", content='" + content + '\'' +
                '}';
    }
}